<?php

namespace NextDeveloper\Accounting\Services;

use NextDeveloper\Accounting\Services\AbstractServices\AbstractCreditCardsService;

/**
 * This class is responsible from managing the data for CreditCards
 *
 * Class CreditCardsService.
 *
 * @package NextDeveloper\Accounting\Database\Models
 */
class CreditCardsService extends AbstractCreditCardsService
{

    // EDIT AFTER HERE - WARNING: ABOVE THIS LINE MAY BE REGENERATED AND YOU MAY LOSE CODE

    public static function create(array $data)
    {
        $data['name']   =  '**** **** **** ' . substr($data['cc_number'], -4);

        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
